name: Darcy model (not simulation!)
height: 0.3
mesh-size: 20
conductivity:
    note: General conductivity
    k: 2e-9
    nu: 1e-3
unsaturated:
    type: Van Genuchten
    alpha: 3.0
    n: 1.5e0
    thetar: 1e-4
    thetas: 0.3
inlet:
    type: Constant
    rate: 20.0
